project_id = "nlrtpectlljrghutjknp"

[functions.ai-chat]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.sync-crm-sheets]
verify_jwt = false

[functions.wiki-ai-search]
verify_jwt = false

[functions.crm-ai-search]
verify_jwt = false

[functions.generate-video-script]
verify_jwt = false

[functions.translate-resume]
verify_jwt = false

[functions.sync-crm-user]
verify_jwt = false

[functions.sync-projects-sheets]
verify_jwt = false

[functions.notify-project-response]
verify_jwt = false
